"""Fix userid/Remove relationship to recipe from grocery list item

Revision ID: 0b4a91da89c7
Revises: 28f466a2c6aa
Create Date: 2023-03-10 15:20:06.621264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4a91da89c7'
down_revision = '28f466a2c6aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grocery_list_user_id_fkey', 'grocery_list', type_='foreignkey')
    op.create_foreign_key(None, 'grocery_list', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('grocery_list_item', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('grocery_list_item', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('grocery_list_item', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint('grocery_list_item_grocery_list_id_fkey', 'grocery_list_item', type_='foreignkey')
    op.drop_constraint('grocery_list_item_ingredient_id_fkey', 'grocery_list_item', type_='foreignkey')
    op.create_foreign_key(None, 'grocery_list_item', 'grocery_list', ['grocery_list_id'], ['id'], ondelete='CASCADE')
    op.drop_column('grocery_list_item', 'ingredient_id')
    op.drop_column('grocery_list_item', 'extra_message')
    op.drop_constraint('ingredient_recipe_id_fkey', 'ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('meal_plan_item_user_id_fkey', 'meal_plan_item', type_='foreignkey')
    op.drop_constraint('meal_plan_item_recipe_id_fkey', 'meal_plan_item', type_='foreignkey')
    op.create_foreign_key(None, 'meal_plan_item', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_column('meal_plan_item', 'user_id')
    op.drop_constraint('recipe_user_id_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('step_recipe_id_fkey', 'step', type_='foreignkey')
    op.create_foreign_key(None, 'step', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tag_user_id_fkey', 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key('tag_user_id_fkey', 'tag', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.create_foreign_key('step_recipe_id_fkey', 'step', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_user_id_fkey', 'recipe', 'user', ['user_id'], ['id'])
    op.add_column('meal_plan_item', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meal_plan_item', type_='foreignkey')
    op.create_foreign_key('meal_plan_item_recipe_id_fkey', 'meal_plan_item', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key('meal_plan_item_user_id_fkey', 'meal_plan_item', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_foreign_key('ingredient_recipe_id_fkey', 'ingredient', 'recipe', ['recipe_id'], ['id'])
    op.add_column('grocery_list_item', sa.Column('extra_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('grocery_list_item', sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grocery_list_item', type_='foreignkey')
    op.create_foreign_key('grocery_list_item_ingredient_id_fkey', 'grocery_list_item', 'ingredient', ['ingredient_id'], ['id'])
    op.create_foreign_key('grocery_list_item_grocery_list_id_fkey', 'grocery_list_item', 'grocery_list', ['grocery_list_id'], ['id'])
    op.drop_column('grocery_list_item', 'comment')
    op.drop_column('grocery_list_item', 'unit')
    op.drop_column('grocery_list_item', 'quantity')
    op.drop_constraint(None, 'grocery_list', type_='foreignkey')
    op.create_foreign_key('grocery_list_user_id_fkey', 'grocery_list', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
