"""Removed thumbnail_url column

Revision ID: 0e0eda0f8cef
Revises: f9f4de2e0b41
Create Date: 2023-11-06 14:45:27.757662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0eda0f8cef'
down_revision = 'f9f4de2e0b41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocery_list_item', 'thumbnail_url')
    op.drop_column('recipe', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('grocery_list_item', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
