"""Added association proxies and relationships

Revision ID: 0f313efe6e3d
Revises: 261e78d665b1
Create Date: 2023-03-08 15:47:57.424465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f313efe6e3d'
down_revision = '261e78d665b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grocery_list_item', 'grocery_list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grocery_list_item', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meal_plan_item', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('step', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meal_plan_item', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grocery_list_item', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grocery_list_item', 'grocery_list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
