"""Recipe id not nullable

Revision ID: 261e78d665b1
Revises: 380e6368dfa7
Create Date: 2023-03-08 15:26:32.623554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261e78d665b1'
down_revision = '380e6368dfa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
