"""Cascade deletes

Revision ID: 28f466a2c6aa
Revises: 71cb8630deeb
Create Date: 2023-03-10 13:29:29.593662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f466a2c6aa'
down_revision = '71cb8630deeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_tag_assoc_tag_id_fkey', 'recipe_tag_assoc', type_='foreignkey')
    op.drop_constraint('recipe_tag_assoc_recipe_id_fkey', 'recipe_tag_assoc', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_tag_assoc', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_tag_assoc', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_tag_assoc', type_='foreignkey')
    op.drop_constraint(None, 'recipe_tag_assoc', type_='foreignkey')
    op.create_foreign_key('recipe_tag_assoc_recipe_id_fkey', 'recipe_tag_assoc', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key('recipe_tag_assoc_tag_id_fkey', 'recipe_tag_assoc', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###
