"""User id not nullable

Revision ID: 380e6368dfa7
Revises: b54b4cc9cc64
Create Date: 2023-03-08 14:55:53.137102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380e6368dfa7'
down_revision = 'b54b4cc9cc64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grocery_list', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meal_plan_item', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recipe', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipe', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meal_plan_item', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grocery_list', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
