"""Made tag 'name' attribute unique

Revision ID: 4c02c3379606
Revises: 0b4a91da89c7
Create Date: 2023-03-13 07:08:01.740562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c02c3379606'
down_revision = '0b4a91da89c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_list_item', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('grocery_list_item', 'thumbnail_url')
    # ### end Alembic commands ###
