"""Tags should be unqiue per user not globally

Revision ID: 71c69b4933eb
Revises: 0e0eda0f8cef
Create Date: 2023-11-10 13:31:41.493731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c69b4933eb'
down_revision = '0e0eda0f8cef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_name_key', 'tag', type_='unique')
    op.create_unique_constraint(None, 'tag', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.create_unique_constraint('tag_name_key', 'tag', ['name'])
    # ### end Alembic commands ###
