"""Added recipe/tag  relationships

Revision ID: 71cb8630deeb
Revises: 0f313efe6e3d
Create Date: 2023-03-10 12:18:23.424303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cb8630deeb'
down_revision = '0f313efe6e3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
