"""Made meal_plan_item's 'recipe' and 'servings' attributes not nullable

Revision ID: 85569448052e
Revises: 4c02c3379606
Create Date: 2023-03-14 16:28:43.224953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85569448052e'
down_revision = '4c02c3379606'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
