"""Made grocery_list_item 'active' and 'extra_items' attributes not nullable

Revision ID: 91d38c32c4ec
Revises: 3dcdbdaed34e
Create Date: 2023-03-15 11:41:01.565815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d38c32c4ec'
down_revision = '3dcdbdaed34e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grocery_list_item', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('grocery_list_item', 'extra_items',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grocery_list_item', 'extra_items',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('grocery_list_item', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
