"""Changed meal_plan_item date column type

Revision ID: b54b4cc9cc64
Revises: c6fe0a3d6056
Create Date: 2023-03-06 17:54:22.833974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54b4cc9cc64'
down_revision = 'c6fe0a3d6056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'servings',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'servings',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
