"""Added columns to 'user' table

Revision ID: c6fe0a3d6056
Revises: daee5af6f20c
Create Date: 2023-03-01 23:03:11.793510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fe0a3d6056'
down_revision = 'daee5af6f20c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
