"""Make many columns not nullable

Revision ID: d76f89b77dba
Revises: 91d38c32c4ec
Create Date: 2023-03-29 20:55:46.955430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76f89b77dba'
down_revision = '91d38c32c4ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grocery_list', 'extra_items',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grocery_list_item', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grocery_list_item', 'servings',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingredient', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingredient', 'input',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meal_plan_item', 'meal_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'servings_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'nutrition',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('recipe', 'nutrition',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipe', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipe', 'servings_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipe', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meal_plan_item', 'meal_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ingredient', 'input',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ingredient', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grocery_list_item', 'servings',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grocery_list_item', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grocery_list', 'extra_items',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
