"""Changed grocery_list_item quantity type to float

Revision ID: fbcb2e918c0e
Revises: 71c69b4933eb
Create Date: 2024-01-29 14:48:51.835741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcb2e918c0e'
down_revision = '71c69b4933eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
